#ifndef PARAMETROS_AG_H_INCLUDED
#define PARAMETROS_AG_H_INCLUDED

#ifndef NUMERO_DE_GERACOES
    #define NUMERO_DE_GERACOES 10
#endif

#ifndef DIMENSOES_PROBLEMA
    #define DIMENSOES_PROBLEMA 1024
#endif

#ifndef TAMANHO_POPULACAO
    #define TAMANHO_POPULACAO 1000
#endif

#ifndef TAMANHO_VALOR
    #define TAMANHO_VALOR 8
#endif

#define TAMANHO_INDIVIDUO DIMENSOES_PROBLEMA*TAMANHO_VALOR
//#define TAMANHO_INDIVIDUO DIMENSOES_PROBLEMA

#define CRITERIO_DE_PARADA  n >= NUMERO_DE_GERACOES

#ifndef TAXA_DE_MUTACAO
    #define TAXA_DE_MUTACAO 0.001
#endif

#ifndef TAXA_DE_RECOMBINACAO
    #define TAXA_DE_RECOMBINACAO 0.8
#endif

#ifndef TAMANHO_TORNEIO
    #define TAMANHO_TORNEIO 3
#endif

#ifndef ELITE
    #define ELITE 5
#endif

#endif // PARAMETROS_AG_H_INCLUDED
