#ifndef PARAMETROS_H_
#define PARAMETROS_H_

#define ONE_MAX 1
#define ELIPSOIDAL 2
#define ROSENBROCK 3

#define FUNCAO_OBJETIVO ONE_MAX
#define MAXIMIZACAO 1

#define TAMANHO_POPULACAO 16384
#define GERACOES 50
#define DIMENSOES 128
#define BITS_POR_DIMENSAO 1
#define BITS_POR_PARAMETRO 8
//#define TAMANHO_ANTICORPO BITS_POR_DIMENSAO*DIMENSOES
#define TAMANHO_ANTICORPO (DIMENSOES*BITS_POR_DIMENSAO/32)
#define FATOR_MUTACAO 3.5  //Parâmetro "rho"
#define FATOR_CLONAGEM 0.1
#define NCLONES 10
#define NALEATORIO 1
#define LIMITE_INFERIOR (-10)
#define LIMITE_SUPERIOR (10)

#define MAX_POPSIZE 16384
#define MAX_ANTIBODYSIZE 4

#define BITS_PER_WORD 32

#endif /* PARAMETROS_H_ */
